* Install From Git Repository
This is only recommended for "pros": you are familiar with git and want to explore the source code.  This method requires that the  [[software_dependencies.org][Software Dependencies]] are already installed.
** Download source code repository
   1. ~git clone https://github.com/granek/aimhii.git~

At this point there are several options for installing aimhii from the downloaded repository.  In both cases it is recommended to first follow the instructions to /Setup a Python Virtual Environment/ in the  [[pip_install_aimhii.org][Pip Installation]] section:
*** Use pip to install from the git repository (Recommended)
1. ~pip install numpy~ (HTSeq needs numpy installed beforehand)
2. ~pip install ./aimhii~
*** Distutils install
1. ~cd aimhii~
2. ~python setup.py install~
** To reproduce the analysis from the manuscript (Optional)
   1. ~cd aimhii~
   2. ~make run_subset~ to do a test analysis on a subset of the data. 
   3. ~make run_aimhii~ to perform the full analysis from the manuscript. 
