* Pip Installation
This requires that the [[software_dependencies.org][Software Dependencies]] are already installed, except for the /Python library dependencies/ which pip will install if missing.
This is recommended for a server with common bioinformatics software already installed, which is likely to include these dependencies.

*Note* that in the instructions below, text that has ~this formatting~ should be typed at the command line.

## It is strongly recommended, but not required to follow the instructions to first [[Setup a Python Virtual Environment]].
** Setup a Python Virtual Environment
This step is optional, but strongly recommended.
This assumes you have Python [[https://pypi.python.org/pypi/pip][pip]] and [[https://pypi.python.org/pypi/virtualenv][virtualenv]] installed.  If [[https://pypi.python.org/pypi/virtualenv][virtualenv]] is not installed try the command ~pip install virtualenv~ to install it.  If [[https://pypi.python.org/pypi/pip][pip]] is not installed, you will need to [[https://pip.pypa.io/en/stable/installing.html][install]] it first.
   
   1. ~virtualenv aimhii_venv~ to set up a virtual environment (see [[http://docs.python-guide.org/en/latest/dev/virtualenvs/][virtualenv guide]] for details).  *Note:* If the default version of python on your system is older than 2.7, you might need to specify the path to python2.7, for example: ~virtualenv -p /usr/local/bin/python2.7 aimhii_venv~
   2. ~source aimhii_venv/bin/activate~ to enter the virtual environment.  Use the command ~deactivate~ to leave virtual environment.
** Use pip to install AIMHII
   1. ~pip install numpy~ (HTSeq needs numpy installed beforehand)
   2. ~pip install aimhii~
** To reproduce the analysis from the manuscript (Optional)
   1. ~git clone https://granek@bitbucket.org/granek/aimhii.git~
   2. ~cd aimhii~
   3. ~make run_subset~ to do a test analysis on a subset of the data. 
   4. ~make run_aimhii~ to perform the full analysis from the manuscript. 
