:CONFIG:
#+TODO: TODO WORKING DRAFT | DONE
#+DRAWERS: HIDDEN PROPERTIES STATE NOTES CONFIG
#+STARTUP: indent showall
#+TAGS:noexport(n)
#+OPTIONS: H:2
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+OPTIONS: skip:nil
#+OPTIONS: todo:nil
#+OPTIONS: author:t
#+OPTIONS: dated:nil 
#+OPTIONS: tags:nil
#+OPTIONS: ^:nil
#+TITLE:AIM-HII
:END:

There are several different ways to install AIM-HII:


1. [[docker_install_aimhii.org][Docker]]: recommended for a standard desktop
2. [[pip_install_aimhii.org][Pip]]: recommended for a bioinformatics server
3. [[git_install_aimhii.org][Git]]: recommended for pros

The bioinformatics software that AIM-HII depends on is described in the  [[software_dependencies.org][Software Dependencies]] section.

For details about the input files to AIM-HII, and options see [[running_aimhii.org][Running AIMHII]].  There are some differences specific to running from Docker that are discussed in /Quick Start to analyze your own data/ section of the [[docker_install_aimhii.org][Docker Installation Instructions]].

Note that in the instructions, text that has ~this formatting~ should be typed at the command line.

* Citation
If you use AIMHII, please cite the publication: 

Esher SK, Granek JA, Alspaugh JA. Rapid mapping of insertional mutations to probe cell wall regulation in Cryptococcus neoformans. /Fungal Genet Biol/. 2015 Sep;82:9-21. doi: [[https://doi.org/10.1016/j.fgb.2015.06.003][10.1016/j.fgb.2015.06.003]]. Epub 2015 Jun 23. PMID: [[https://pubmed.ncbi.nlm.nih.gov/26112692/][26112692]]; PMCID: [[http://www.ncbi.nlm.nih.gov/pmc/articles/pmc4693612/][PMC4693612]].
